% DataexplorerApi - Search operations
%
% DataexplorerApi Properties:
%    apiClient - ApiClient instance
%
% DataexplorerApi Methods
%    search - Perform a search query
classdef DataexplorerApi < handle
    % NOTE: This file is auto generated by the swagger code generator program.
    % Do not edit the file manually.
    properties
        apiClient
        context_
    end
    methods
        function obj = DataexplorerApi(apiClient, context)
            obj.apiClient = apiClient;
            obj.context_ = context;
        end

        function [returnData, resp] = search(obj, body, varargin)
            % Perform a search query
            % body (SearchQuery)
            % simple (logical)
            % size (integer)
            % returns: [vector[SearchResponse], resp]

            x__inp = inputParser;
            x__inp.StructExpand = false;
            addRequired(x__inp, 'body');
            addParameter(x__inp, 'simple', []);
            addParameter(x__inp, 'size', []);
            addParameter(x__inp, 'DumpResponseData', false);
            parse(x__inp, body, varargin{:});

            % Path parameters
            pathParams = {};

            % Query parameters
            queryParams = {};
            if ~isempty(x__inp.Results.simple)
                queryParams = [queryParams, 'simple', flywheel.ApiClient.castParam(x__inp.Results.simple, 'logical')];
            else
                queryParams = [queryParams, 'simple', 'true'];
            end
            if ~isempty(x__inp.Results.size)
                queryParams = [queryParams, 'size', flywheel.ApiClient.castParam(x__inp.Results.size, 'integer')];
            else
                queryParams = [queryParams, 'size', '100'];
            end

            % Header parameters
            headers = {};

            % Form parameters
            formParams = {};
            files = {};

            % Body (as JSON)
            body = flywheel.model.SearchQuery.ensureIsInstance(x__inp.Results.body);
            body = flywheel.ApiClient.encodeJson(body.toJson());

            resp = obj.apiClient.callApi('POST', '/dataexplorer/search', ...
                pathParams, queryParams, headers, body, formParams, files);

            status = resp.getStatusCode();

            switch num2str(status)
                case '200'
                    if x__inp.Results.DumpResponseData
                        x__respData = resp.getBodyAsString();
                        disp(x__respData);
                    end
                    json = flywheel.ApiClient.getResponseJson(resp);
                    returnData = flywheel.ModelBase.cellmap(@(x) flywheel.model.SearchResponse.fromJson(x, obj.context_), json);
                otherwise
                    returnData = [];
            end
        end

    end
end
