function  dr_fwWriteMrtrixTck(myfg, fpn)
    tractData = struct(...
                    'act', ['999'], ...
              'backtrack', '999', ...
      'downsample_factor', '999', ...
              'fod_power', '999', ...
         'init_threshold', '999', ...
                   'lmax', '999', ...
              'max_angle', '999', ...
       'max_num_attempts', '999', ...
         'max_num_tracks', '999', ...
      'max_seed_attempts', '999', ...
             'max_trials', '999', ...
                 'method', '999', ...
         'mrtrix_version', '999', ...
       'output_step_size', '999', ...
                    'rk4', '999', ...
       'samples_per_step', '999', ...
         'sh_precomputed', '999', ...
                 'source', ['Converted from Matlab .mat'], ...
              'step_size', '999', ...
    'stop_on_all_include', '999', ...
              'threshold', '999', ...
              'timestamp', '999', ...
         'unidirectional', '999', ...
               'datatype', '999', ...
                  'count', num2str(size(cellfun(@transpose,myfg.fibers,'un',0), 1)), ...
            'total_count', '0', ...
                   'data', {cellfun(@transpose,myfg.fibers,'un',0)'} );

      tractData.data = cellfun(@transpose,myfg.fibers,'un',0)';
      write_mrtrix_tracks(tractData, fpn);
end

