% ConfigFeatureMap - A map of supported features
%
% ConfigFeatureMap Properties:
%    signedUrl   - Whether or not this server supports signed url uploads
%    jobTickets  - Whether or not this server supports new job tickets
%
% ConfigFeatureMap Methods:
%    toJson - Convert the object to a Map that can be encoded to json
%    struct - Convert the object to a struct
    classdef ConfigFeatureMap < flywheel.ModelBase
    % NOTE: This file is auto generated by the swagger code generator program.
    % Do not edit the file manually.
    properties (Constant)
        propertyMap = containers.Map({ 'signedUrl', 'jobTickets' }, ...
            { 'signed_url', 'job_tickets' });
    end
    properties(Dependent)
        signedUrl
        jobTickets
    end
    methods
        function obj = ConfigFeatureMap(varargin)
            obj@flywheel.ModelBase(flywheel.model.ConfigFeatureMap.propertyMap);

            % Allow empty object creation
            if length(varargin)
                p = inputParser;
                addParameter(p, 'signedUrl', []);
                addParameter(p, 'jobTickets', []);

                parse(p, varargin{:});

                if ~isempty(p.Results.signedUrl)
                    obj.props_('signed_url') = p.Results.signedUrl;
                end
                if ~isempty(p.Results.jobTickets)
                    obj.props_('job_tickets') = p.Results.jobTickets;
                end
            end
        end
        function result = get.signedUrl(obj)
            if ismethod(obj, 'get_signedUrl')
                result = obj.get_signedUrl();
            else
                if isKey(obj.props_, 'signed_url')
                    result = obj.props_('signed_url');
                else
                    result = [];
                end
            end
        end
        function obj = set.signedUrl(obj, value)
            obj.props_('signed_url') = value;
        end
        function result = get.jobTickets(obj)
            if ismethod(obj, 'get_jobTickets')
                result = obj.get_jobTickets();
            else
                if isKey(obj.props_, 'job_tickets')
                    result = obj.props_('job_tickets');
                else
                    result = [];
                end
            end
        end
        function obj = set.jobTickets(obj, value)
            obj.props_('job_tickets') = value;
        end
        function result = toJson(obj)
            result = containers.Map;
            if isKey(obj.props_, 'signed_url')
                result('signed_url') = flywheel.ModelBase.serializeValue(obj.props_('signed_url'), 'logical');
            end
            if isKey(obj.props_, 'job_tickets')
                result('job_tickets') = flywheel.ModelBase.serializeValue(obj.props_('job_tickets'), 'logical');
            end
        end
        function result = struct(obj)
            result = struct;

            if isKey(obj.props_, 'signed_url')
                result.signedUrl = obj.props_('signed_url');
            else
                result.signedUrl = [];
            end
            if isKey(obj.props_, 'job_tickets')
                result.jobTickets = obj.props_('job_tickets');
            else
                result.jobTickets = [];
            end
        end
        function result = returnValue(obj)
            result = obj;
        end
    end
    methods(Access = protected)
        function prpgrp = getPropertyGroups(obj)
            if ~isscalar(obj)
                prpgrp = getPropertyGroups@matlab.mixin.CustomDisplay(obj);
            else
                propList = struct;
                if isKey(obj.props_, 'signed_url')
                    propList.signedUrl = obj.props_('signed_url');
                else
                    propList.signedUrl = [];
                end
                if isKey(obj.props_, 'job_tickets')
                    propList.jobTickets = obj.props_('job_tickets');
                else
                    propList.jobTickets = [];
                end
                prpgrp = matlab.mixin.util.PropertyGroup(propList);
            end
        end
    end
    methods(Static)
        function obj = fromJson(json, context)
            obj =  flywheel.model.ConfigFeatureMap;
            if isfield(json, 'signed_url')
                obj.props_('signed_url') = flywheel.ModelBase.deserializeValue(json.signed_url, 'logical');
            end
            if isfield(json, 'job_tickets')
                obj.props_('job_tickets') = flywheel.ModelBase.deserializeValue(json.job_tickets, 'logical');
            end
            if isprop(obj, 'context_')
                obj.setContext_(context);
            end
        end
        function obj = ensureIsInstance(obj)
            if ~isempty(obj)
                % Realistically, we only convert structs
                if ~isa(obj, 'flywheel.model.ConfigFeatureMap')
                    obj = flywheel.model.ConfigFeatureMap(obj);
                end
                if isKey(obj.props_, 'signed_url')
                end
                if isKey(obj.props_, 'job_tickets')
                end
            end
        end
    end
end
